default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

joint_limits:
  # velocity = deg/sec acceleration = deg/sec^2
  joint_1:
    has_velocity_limits: true
    max_velocity: 5.026
    has_acceleration_limits: true
    max_acceleration: 11.693

  joint_2:
    has_velocity_limits: true
    max_velocity: 4.188
    has_acceleration_limits: true
    max_acceleration: 10.472

  joint_3:
    has_velocity_limits: true
    max_velocity: 5.183
    has_acceleration_limits: true
    max_acceleration: 12.950

  joint_4:
    has_velocity_limits: true
    max_velocity: 6.562
    has_acceleration_limits: true
    max_acceleration: 13.406

  joint_5:
    has_velocity_limits: true
    max_velocity: 6.963
    has_acceleration_limits: true
    max_acceleration: 17.400

  joint_6:
    has_velocity_limits: true
    max_velocity: 10.472
    has_acceleration_limits: true
    max_acceleration: 26.179